<?php

namespace ContainerDyDdjHc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_NWRvQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.NW_Rv_Q' shared service.
     *
     * @return \App\Controller\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DefaultController::home()": the $security argument is type-hinted with the non-existent class or interface: "App\\Controller\\Security". Did you forget to add a use statement?');
    }
}
