<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM9sXUqW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM9sXUqW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM9sXUqW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM9sXUqW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM9sXUqW\App_KernelDevDebugContainer([
    'container.build_hash' => 'M9sXUqW',
    'container.build_id' => '5c17c0e3',
    'container.build_time' => 1731580631,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM9sXUqW');
