<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJzvmqhx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJzvmqhx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJzvmqhx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJzvmqhx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJzvmqhx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jzvmqhx',
    'container.build_id' => 'e6096b7e',
    'container.build_time' => 1729862996,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJzvmqhx');
