<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRib7VR0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRib7VR0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRib7VR0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRib7VR0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRib7VR0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rib7VR0',
    'container.build_id' => '32768a07',
    'container.build_time' => 1727693888,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRib7VR0');
