version: '3'

services:
  nodejs-api:
    build: ./moc-node
    ports:
      - "3999:3000"
    environment:
      - MONGODB_URI=mongodb+srv://ruben:vlLm7256@cluster01.uh3hpew.mongodb.net/

  symfony-app:
    build: ./moc-symfony
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - moc-symfony

volumes:
  mongodb_data:



